apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  db: myapp
  host: postgres
  port: "5432"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: 'cm9vdA=='
  password: 'bXktc2VjcmV0LXB3'
