{
 "title": "Homework 03",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Metrics from APP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (uri) (rate(http_server_requests_seconds_count{application=\"user-service\"}[1m]))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(status) (increase(http_server_requests_seconds_count{application=\"user-service\", status=~\"[4|5].+\"}[1m]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum by(uri,le) (rate(http_server_requests_seconds_bucket{application=\"user-service\"}[1m])))*1000",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Latency (99 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(uri,le) (rate(http_server_requests_seconds_bucket{application=\"user-service\"}[1m])))*1000",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Latency (90 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by(uri,le) (rate(http_server_requests_seconds_bucket{application=\"user-service\"}[1m])))*1000",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Latency (50 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(uri,le) (rate(http_server_requests_seconds_bucket{application=\"user-service\"}[1m])))*1000",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics from nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"user-service\"}[1m]))",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(status) (increase(nginx_ingress_controller_request_duration_seconds_count{ingress=\"user-service\", status=~\"[4|5].+\"}[1m]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum by (path, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"user-service\"}[1m])))*1000",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Latency (99 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (path, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"user-service\"}[1m])))*1000",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Latency (90 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by (path, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"user-service\"}[1m])))*1000",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Latency (50 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (path, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"user-service\"}[1m])))*1000",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (datname) (pg_database_size_bytes)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum by (server) (pg_settings_max_connections)",
       "legendFormat": "max"
      },
      {
       "expr": "sum by (server) (pg_settings_superuser_reserved_connections) + sum by (server) (pg_stat_activity_count) ",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Max duration active transaction",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_activity_max_tx_duration{state=\"active\"}[1m]))",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Locks Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_locks_count[1m]))",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"user-service.*\", node=~\"minikube\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (node_namespace_pod_container:container_memory_working_set_bytes{pod=~\"user-service.*\", container!=\"\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}