fullnameOverride: postgres

postgresqlUsername: root
postgresqlPassword: my-secret-pw
postgresqlDatabase: myapp

service:
  type: NodePort
  port: 5432

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 256Mi