apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  db-url: 'jdbc:postgresql://postgres/myapp'

---

apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  db-username: 'cm9vdA=='
  db-password: 'bXktc2VjcmV0LXB3'