spring:
  application.name: user-service
  main.banner-mode: off

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql.init.mode: never

management:
  endpoints:
    web:
      exposure:
        include: health, env, info, metrics, prometheus

  endpoint:
    health:
      probes.enabled: true
      group:
        readiness:
          include: readinessState, db
      show-details: always

    info.enabled: true
    env.enabled: true
    prometheus.enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      slo:
        http.server.requests: 5ms, 10ms, 20ms, 50ms, 100ms, 1s, 5s
    export:
      prometheus:
        enabled: true