spring:
  application.name: user-service
  main.banner-mode: off

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql.init.mode: never

management:
  endpoints:
    web:
      exposure:
        include: health, env

  endpoint:
    health:
      probes.enabled: true
      group:
        readiness:
          include: readinessState, db
      show-details: always
