apiVersion: v1
kind: Service
metadata:
  name: {{ template "user-service.serviceName" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: app
  selector:
    {{- include "user-service.selectorLabels" . | nindent 4 }}
